name: prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  injectable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  injectable_generator: ^3.1.1
  freezed: ^4.0.0-dev.3

flutter:
  uses-material-design: true
